language: node_js
node_js:
  - "node"
before_install:
  - pip install --user codecov
script:
  - npm run test:cc
after_success:
  - codecov --file coverage/lcov.info --disable search
  - bash publish-docker-img.sh
