version: '3'

services:
  deploy:
    image: vpn2go-frontend
    build:
      context: .
      args:
        - API_URL=${API_URL}
    restart: always
    ports:
      - '127.0.0.1:${PORT_FRONTEND}:80'
